### GET request to get Mangas.
GET https://react.ddev.site/api/manga?include=thumbnail&jsonapi_include=1
Accept: application/json

### GET request to get individual Manga by its ID.
GET https://react.ddev.site/api/manga/{ID}?include=thumbnail&jsonapi_include=1
Accept: application/json

### GET request to get individual Manga Chapter by its ID.
GET https://react.ddev.site/api/manga/chapter{ID}?include=frames.frame&jsonapi_include=1
Accept: application/json
