name: 'TSX Coding standards validation'

on: pull_request

jobs:
  eslint-checker:
    name: 'ESLint Code standards validation'
    runs-on: ubuntu-latest
    env:
      WEBSITE_ROOT: "web"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install drupal project
        run: |
          composer install

      - name: Node JS installer
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: .github/tools/package-lock.json

      - name: Install Yarn
        run: |
          npm -v
          npm install yarn

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install ESlint
        run: |
          yarn --cwd ./.github/tools/ add --dev \
          eslint-config-drupal-bundle \
          eslint
          @typescript-eslint/parser
          eslint-plugin-react-hooks
          eslint-plugin-react-refresh
          typescript-eslint

      - name: Installing reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Configuring diff file.
        run: |
          git config --global --add safe.directory .
          git diff origin/$GITHUB_BASE_REF origin/$GITHUB_HEAD_REF --name-only -- '***.tsx*' |\
          grep -e $WEBSITE_ROOT/app |\
          tr "\n" " " > /tmp/check

      - name: TSX coding standards checking
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./.github/tools/node_modules/.bin/eslint `cat /tmp/check` \
          --ext tsx --report-unused-disable-directives --max-warnings 0 |
          reviewdog -f=eslint -name="ESLint" \
          -reporter=github-pr-review \
          -fail-on-error -filter-mode=nofilter -tee
        timeout-minutes: 5
