name: 'PHP Coding standards validation'

on: pull_request

jobs:
  phpcs-checker:
    name: 'PHPCS Coding standards validation'
    runs-on: ubuntu-latest
    env:
      WEBSITE_ROOT: "web"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Installing PHPCS
        run: |
          composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer global require drupal/coder
          composer install

      - name: Installing reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      
      - name: Configuring diff file.
        run: |
          git config --global --add safe.directory .
          git diff --name-only -r origin/$GITHUB_BASE_REF origin/$GITHUB_HEAD_REF |\
          grep -e $WEBSITE_ROOT/modules/custom -e $WEBSITE_ROOT/themes/custom -e $WEBSITE_ROOT/profiles/custom |\
          tr "\n" " " > /tmp/check

      - name: Checking php Drupal standards
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ~/.composer/vendor/bin/phpcs -i
          /bin/bash ./.github/scripts/phpcs_code_checking.sh
    timeout-minutes: 5
